### ISSUE TITLE
JWTLogin setting

### ISSUE THREAD

**Issue by BearandYoon** [fongandrew/meteor-jwt-login#1]
Hello @fongandrew 
I am a new on MeteorJS and need to log in with email.
I've created the token with https://github.com/auth0/node-jsonwebtoken and then send that with email on the server side so I can get the token on the client side.
I need to log in with that token on the client side.
I think meteor-jwt-login lib is useful for me but I am not sure about the JWTLogin setting.
Can you give me details for the JWTLogin setting?

This code is to generate the token on the server side.
```
            let token = jwt.sign({
                data: customerUser.emails[0].address
            }, Meteor.settings.public.token_secret, { expiresIn: '8h' });
```

This is the code that verifies the token on the client side.
```
                        jwt.verify($stateParams.token, Meteor.settings.public.token_secret, async function(err, decoded) {
                            if (err) {
                                $state.go('accounts.login');
                            } else {
                                // log in with token
                            }
                        });
```

**Comment by fongandrew** [comment]
Whoa .... `token_secret` should definitely *not* be in `Meteor.settings.public`! As the name suggests, the token should be secret and `settings.public` is public. The secret is shared across *all* your users, so exposing it is a huge security vulnerability (it allows anyone to login as anyone else).

JWT verification should only happen on the server, not the client. You can use `Accounts. loginWithJWT` to post back from the client to the server. Or you can use a Meteor method.

Please note that this package isn't actively maintained (I don't use Meteor currently) so it's very much a use-at-your-own-risk situation. If you're not confident about how JWTs work, I advise just sticking with Meteor's built-in password login systems.
